---
title: "Negative dataset comparison"
author: "Katarzyna Sidorczuk"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 8, message = FALSE, warning = FALSE)

library(biogram)
library(ggplot2)
library(tidyr)
library(ggbiplot)
library(dplyr)
library(seqR)
library(fmsb)
library(ggdendro)
library(gridExtra)
library(tsne)
library(targets)

source("../functions/plot_functions.R")

props <- data.frame(prop = c("BIGC670101", "ARGP820101", "CHAM820101", "CHOP780201", "CHOP780202", 
                             "CHOP780203", "FASG760101", "FASG760104", "FASG760105", "FAUJ880103", 
                             "KLEP840101", "KYTJ820101", "ZIMJ680103", "ENGD860101", "FASG890101"),
                    description = c("Residue volume (Bigelow, 1967)", "Hydrophobicity index (Argos et al., 1982)",
                                    "Polarizability parameter (Charton-Charton, 1982)", "Normalized frequency of alpha-helix (Chou-Fasman, 1978b)",
                                    "Normalized frequency of beta-sheet (Chou-Fasman, 1978b)", "Normalized frequency of beta-turn (Chou-Fasman, 1978b)",
                                    "Molecular weight (Fasman, 1976)", "pK-N (Fasman, 1976)", "pK-C (Fasman, 1976)", 
                                    "Normalized van der Waals volume (Fauchere et al., 1988)", "Net charge (Klein et al., 1984)",
                                    "Hydropathy index (Kyte-Doolittle, 1982)", "Polarity (Zimmerman et al., 1968)",
                                    "Hydrophobicity index (Engelman et al., 1986)", "Hydrophobicity index (Fasman, 1989)"))

if(Sys.info()[["nodename"]] %in% c("amyloid", "phobos", "huawei")) {
  data_path <- "/home/michal/Dropbox/BioNgramProjects/NegativeDatasets/Datasets/"
}
if(Sys.info()[["nodename"]] == "ryzen") {
  data_path <- "~/Dropbox/Projekty/BioNgramProjects/NegativeDatasets/Datasets/"
}
if(Sys.info()[["nodename"]] == "kasia-MACH-WX9") {
  data_path <- "/media/kasia/Data/Dropbox/Projekty/BioNgramProjects/NegativeDatasets/Datasets/"
}

withr::with_dir(rprojroot::find_root('_targets.R'), 
                tar_load(c(positive_traintest, methods, dataset_colors, aa_comp_peptides_with_names, 
                           aa_comp_peptides, aa_comp_peptides_pos, aa_comp_peptides_all, aa_comp, 
                           aa_comp_pos, aa_comp_all, df_neg, df_pos, df_all, ngram_counts_sum,
                           ngram_counts_sum_pos, ngram_counts_sum_all)))
```

## Datasets

- 13 methods of sampling
- 5 repetitions

## Numbers of sequences

```{r}
df_all %>% 
  group_by(method, rep) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "rep", values_from = "n") %>% 
  knitr::kable()
```

## Sequence length distributions

```{r fig.height = 10}
ggplot(df_all, aes(x = rep, y = len, group = rep, fill = Dataset)) +
  geom_violin() +
  facet_wrap(~method, scales = "free_y", ncol = 3) +
  xlab("Replication") +
  ylab("Length") +
  scale_fill_manual("Dataset", values = c(Negative = "#76bef2", Positive = "#ff4242")) +
  theme_bw() +
  theme(legend.position = "none")
```

## Amino acid composition

```{r fig.height = 10}

aa_comp_all %>% 
  group_by(Dataset, method, aa) %>% 
  summarise(Frequency = mean(Freq), sd = sd(Freq)) %>% 
  mutate(method = factor(method, levels = names(dataset_colors))) %>% 
  ggplot(aes(x = aa, y = Frequency, fill = Dataset)) +
  geom_col(color = "black", size = 0.25) +
  facet_wrap(~method, nrow = 4) +
  scale_fill_manual("Dataset", values = c(Negative = "#76bef2", Positive = "#ff4242")) +
  geom_errorbar(aes(ymin = Frequency - sd, ymax = Frequency + sd), width=.2,
                position=position_dodge(.9)) + 
  theme_bw() +
  ggtitle("Amino acid composition of datasets generated using different sampling methods") +
  theme(legend.position = "none")
```

```{r fig.height = 10}
aa_comp_all %>% 
  group_by(Dataset, aa, method) %>% 
  dplyr::summarise(Frequency = mean(Freq), sd = sd(Freq)) %>% 
  mutate(method = factor(method, levels = names(dataset_colors))) %>% 
  ggplot(aes(x = method, y = Frequency, fill = Dataset)) +
  geom_col(color = "black", size = 0.25) +
  facet_wrap(~aa, nrow = 4) +
  scale_fill_manual("Dataset", values = c(Negative = "#76bef2", Positive = "#ff4242")) +
  geom_errorbar(aes(ymin = Frequency - sd, ymax = Frequency + sd), width = 0.2,
                position = position_dodge(0.9)) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Differences in amino acid frequency using different sampling methods") +
  theme(legend.position = "none")
```


```{r fig.height = 10}
aa_comp_heatmap_dat <- aa_comp_all %>% 
  pivot_wider(names_from = "aa", values_from = "Freq", values_fill = 0) %>% 
  mutate(Dataset = ifelse(Dataset == "Positive", "Positive", paste0(method, "_rep", rep))) %>% 
  select(-c(method, rep)) 

# aa_comp_heatmap_dat %>% 
#   pivot_longer(1:20, names_to = "Amino acid", values_to = "Frequency") %>% 
#   ggplot(aes(x = `Amino acid`, y = Dataset)) +
#   geom_tile(aes(fill = Frequency)) +
#   scale_fill_gradient2(low = "#ffffff", mid = "#ffe96b",  high = "#ff4242", midpoint = 0.05) +
#   theme_bw() 

clustering_methods <- as.dendrogram(hclust(dist(as.matrix(aa_comp_heatmap_dat[,2:21]))))
methods_order <- order.dendrogram(clustering_methods)

dendro <- clustering_methods %>%
  dendro_data %>%
  segment %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment() +
  scale_y_continuous("") +
  scale_x_discrete("",
                   limits = factor(1L:nobs(clustering_methods))) + 
  theme_void() + 
  coord_flip()

aa_comp_clustered_dat <- pivot_longer(aa_comp_heatmap_dat, 2:21, names_to = "Amino acid", values_to = "Frequency")
aa_comp_clustered_dat[["Dataset"]] <- factor(aa_comp_clustered_dat[["Dataset"]],
                                             levels = aa_comp_heatmap_dat[["Dataset"]][methods_order], ordered = TRUE)

heatmap <- aa_comp_clustered_dat %>% 
  ggplot(aes(x = `Amino acid`, y = Dataset)) +
  geom_tile(aes(fill = Frequency)) +
  scale_fill_gradient2(low = "#ffffff", mid = "#ffe96b",  high = "#ff4242", midpoint = 0.05) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.key.width = unit(2, "lines"))

max_height <- unit.pmax(ggplotGrob(heatmap)[["heights"]],
                        ggplotGrob(dendro)[["heights"]])

grob_list <- list(heatmap = ggplotGrob(heatmap),
                  dendrogram = ggplotGrob(dendro))
grob_list[["heatmap"]][["heights"]] <-
  grob_list[["dendrogram"]][["heights"]] <-
  max_height

grid.arrange(grob_list[["heatmap"]], grob_list[["dendrogram"]], widths = c(0.8, 0.2))
```


```{r}
pca_data_all <- aa_comp_all %>% 
  pivot_wider(names_from = aa, values_from = Freq, values_fill = 0) %>% 
  mutate(method = factor(method, levels = names(dataset_colors)))

pca_res_all <- prcomp(pca_data_all[, 4:ncol(pca_data_all)], center = TRUE, scale = TRUE)

ggbiplot(pca_res_all, choices = 1:2) +
  ggtitle("PCA on amino acid composition with positive dataset") +
  theme_bw() +
  geom_point(aes(color = pca_data_all[["method"]], shape = pca_data_all[["method"]]), size = 3) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Dataset", values = dataset_colors, labels = names(dataset_colors)) +
  scale_shape_manual("Dataset", values = c(17, rep(16, 13)), labels = names(dataset_colors))


pca_data <- aa_comp %>% 
  pivot_wider(names_from = aa, values_from = Freq, values_fill = 0)

pca_res <- prcomp(pca_data[, 3:ncol(pca_data)], center = TRUE, scale = TRUE)

ggbiplot(pca_res, choices = 1:2, groups = pca_data[["method"]]) +
  ggtitle("PCA on amino acid composition") +
  theme_bw() +
  geom_point(aes(color = pca_data[["method"]]), size = 3) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Sampling method", values = dataset_colors)


tsne_res_all <- tsne(pca_data_all[, 4:23], perplexity = 3, max_iter = 1000) %>% 
  as.data.frame() %>% 
  cbind(pca_data_all[, 1:3]) %>% 
  mutate(method = factor(method, levels = names(dataset_colors))) 

ggplot(tsne_res_all, aes(x = V1, y = V2, color = method)) + 
  geom_point(aes(shape = method), size = 3) +
  scale_color_manual("Dataset", values = dataset_colors, labels = names(dataset_colors)) +
  scale_shape_manual("Dataset", values = c(17, rep(16, 13)), labels = names(dataset_colors)) +
  ggtitle("tSNE on amino acid composition") +
  theme_bw()
```

## PCA on bigram and trigram composition

```{r  fig.height = 10}
ngram_counts_sum_all[is.na(ngram_counts_sum_all)] <- 0

pca_ngram_res <- prcomp(select(ngram_counts_sum_all, -c("method", "rep", "Dataset")), center = TRUE, scale = TRUE)

ggbiplot(pca_ngram_res, choices = 1:2, var.axes = FALSE) +
  ggtitle("PCA on bigram and trigram composition") +
  geom_point(aes(color = ngram_counts_sum_all[["method"]], shape = ngram_counts_sum_all[["method"]]), size = 3) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Dataset", values = dataset_colors, labels = names(dataset_colors)) +
  scale_shape_manual("Dataset", values = c(17, rep(16, 13)), labels = names(dataset_colors)) 

ggbiplot(pca_ngram_res, choices = 1:2, var.axes = FALSE, groups = ngram_counts_sum_all[["method"]]) +
  geom_point(aes(color = ngram_counts_sum_all[["method"]], shape = ngram_counts_sum_all[["method"]])) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Dataset", values = dataset_colors) +
  scale_shape_manual("Dataset", values = c(17, rep(16, 13)), labels = names(dataset_colors)) +
  xlim(c(-1, -0.25)) +
  ylim(c(-1, -0.25)) 

# tsne_ngram_res <- tsne(select(ngram_counts_sum_all, -c("method", "rep", "Dataset")), perplexity = 3, max_iter = 1000) %>% 
#   as.data.frame() %>% 
#   cbind(ngram_counts_sum_all[, c("method", "rep", "Dataset")])
# 
# ggplot(tsne_ngram_res, aes(x = V1, y = V2, color = method)) + 
#   geom_point(aes(shape = Dataset), size = 3) +
#   scale_color_manual("Sampling method", values = dataset_colors) +
#   scale_shape_manual("Dataset", values = c(`Negative` = 16, `Positive` = 15)) +
#   ggtitle("tSNE on bigram and trigram composition") +
#   theme_bw()
```

## Statistical significance of differences between replicates of each sampling method

```{r fig.height=10}
# Amino acid composition - replicates
combns <- combn(unique(aa_comp_peptides[["rep"]]), 2, simplify = FALSE)
test_res <- lapply(unique(aa_comp_peptides[["method"]]), function(ith_method) {
  lapply(seq_along(combns), function(ith_combn) {
    test_dat <- filter(aa_comp_peptides, method == ith_method, rep %in% combns[[ith_combn]])
    lapply(unique(aa_comp_peptides[["Amino acid"]]), function(ith_aa) {
      data.frame(method = ith_method,
                 comparison = paste0(combns[[ith_combn]][1], "_", combns[[ith_combn]][2]),
                 aa = ith_aa,
                 pval = wilcox.test(x = filter(test_dat, `Amino acid` == ith_aa, rep == combns[[ith_combn]][1])[["Frequency"]],
                                    y = filter(test_dat, `Amino acid` == ith_aa, rep == combns[[ith_combn]][2])[["Frequency"]],
                                    exact = FALSE)[["p.value"]])
    }) %>% bind_rows() 
  }) %>% bind_rows() %>%
    mutate(pval_adjusted = p.adjust(pval))
}) %>% bind_rows()

test_res %>%
  select(-pval) %>%
  group_by(aa, method) %>%
  summarise(n_signif = sum(pval_adjusted < 0.05)) %>%
  ggplot(aes(x = aa, y = method, fill = n_signif)) +
  geom_tile() +
  ggtitle("Differences in amino acid composition of peptides between replicates")


# Amino acid composition - methods

  
combns <- combn(unique(aa_comp_peptides_all[["method"]]), 2, simplify = FALSE)
test_res_methods <- lapply(seq_along(combns), function(ith_combn) {
  test_dat <- filter(aa_comp_peptides_all, method  %in% combns[[ith_combn]])
  lapply(unique(aa_comp_peptides_all[["Amino acid"]]), function(ith_aa) {
    data.frame(method1 = combns[[ith_combn]][1], 
               method2 = combns[[ith_combn]][2],
               aa = ith_aa,
               pval = wilcox.test(x = filter(test_dat, `Amino acid` == ith_aa, method == combns[[ith_combn]][1])[["Frequency"]],
                                  y = filter(test_dat, `Amino acid` == ith_aa, method == combns[[ith_combn]][2])[["Frequency"]],
                                  exact = FALSE)[["p.value"]])
  }) %>% bind_rows() 
}) %>% bind_rows() %>%
    mutate(pval_adjusted = p.adjust(pval)) %>%
  select(-pval) %>%
  group_by(aa, method1, method2) %>%
  summarise(is_signif = pval_adjusted < 0.05) 

# test_res_methods_heatmap_dat <- test_res_methods %>% 
#   pivot_wider(names_from = "aa", values_from = "is_signif")
# 
# clustering_methods <- as.dendrogram(hclust(dist(as.matrix(test_res_methods_heatmap_dat[,2:ncol(test_res_methods_heatmap_dat)]))))
# methods_order <- order.dendrogram(clustering_methods)
# 
# aa_comp_methods_clustered_dat <- pivot_longer(test_res_methods_heatmap_dat, 2:21, names_to = "Amino acid", values_to = "is_signif")
# aa_comp_methods_clustered_dat[["comparison"]] <- factor(aa_comp_methods_clustered_dat[["comparison"]],
#                                              levels = test_res_methods_heatmap_dat[["comparison"]][methods_order], ordered = TRUE)
# 
# aa_comp_methods_clustered_dat %>% 
#   ggplot(aes(x = `Amino acid`, y = comparison, fill = is_signif)) +
#   geom_tile() +
#   theme_bw() +
#   theme(legend.position = "bottom",
#         legend.key.width = unit(2, "lines"))

ggplot(test_res_methods, aes(x = method1, y = method2, fill = is_signif)) +
  geom_tile(color = "white") +
  facet_wrap(~aa) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual("Is significant", values = c(`FALSE` = "#76bef2", `TRUE` = "#ff4242")) +
  ggtitle("Differences in amino acid composition of peptides between methods and positive dataset")
```

```{r fig.height = 10}
aa_comp_peptides_all %>% 
  group_by(method, `Amino acid`) %>% 
  dplyr::summarise(Mean_frequency = mean(Frequency), sd = sd(Frequency)) %>% 
  mutate(method = factor(method, levels = names(dataset_colors)),
         Dataset = ifelse(method == "Positive", "Positive", "Negative")) %>% 
  ggplot(aes(x = method, y = Mean_frequency, fill = Dataset)) +
  geom_col(color = "black", size = 0.25) +
  facet_wrap(~`Amino acid`, nrow = 4) +
  scale_fill_manual("Dataset", values = c(Negative = "#76bef2", Positive = "#ff4242")) +
  geom_errorbar(aes(ymin = Mean_frequency - sd, ymax = Mean_frequency + sd), width = 0.2,
                position = position_dodge(0.9)) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Differences in amino acid frequency of peptides using different sampling methods") +
  theme(legend.position = "none")



aa_comp_peptides_heatmap_dat <- aa_comp_peptides_all %>% 
  group_by(method, rep, `Amino acid`) %>% 
  dplyr::summarise(mean_frequency = mean(Frequency)) %>% 
  pivot_wider(names_from = "Amino acid", values_from = "mean_frequency", values_fill = 0) %>% 
  mutate(Dataset = ifelse(method == "Positive", "Positive", paste0(method, "_rep", rep))) %>% 
  ungroup() %>% 
  select(-c(method, rep)) 

clustering_methods <- as.dendrogram(hclust(dist(as.matrix(aa_comp_peptides_heatmap_dat[, c("A", "C", "D", "E", "F", "G", "H", 
                                                                                           "I", "K", "L", "M", "N", "P", "Q", 
                                                                                           "R", "S", "T", "V", "W", "Y")]))))
methods_order <- order.dendrogram(clustering_methods)

dendro <- clustering_methods %>%
  dendro_data %>%
  segment %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment() +
  scale_y_continuous("") +
  scale_x_discrete("",
                   limits = factor(1L:nobs(clustering_methods))) + 
  theme_void() + 
  coord_flip()

aa_comp_peptides_clustered_dat <- pivot_longer(aa_comp_peptides_heatmap_dat, A:Y, names_to = "Amino acid", values_to = "Frequency")
aa_comp_peptides_clustered_dat[["Dataset"]] <- factor(aa_comp_peptides_clustered_dat[["Dataset"]],
                                             levels = aa_comp_peptides_heatmap_dat[["Dataset"]][methods_order], ordered = TRUE)

heatmap <- aa_comp_peptides_clustered_dat %>% 
  ggplot(aes(x = `Amino acid`, y = Dataset)) +
  geom_tile(aes(fill = Frequency)) +
  scale_fill_gradient2(low = "#ffffff", mid = "#ffe96b",  high = "#ff4242", midpoint = 0.05) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.key.width = unit(2, "lines"))

max_height <- unit.pmax(ggplotGrob(heatmap)[["heights"]],
                        ggplotGrob(dendro)[["heights"]])

grob_list <- list(heatmap = ggplotGrob(heatmap),
                  dendrogram = ggplotGrob(dendro))
grob_list[["heatmap"]][["heights"]] <-
  grob_list[["dendrogram"]][["heights"]] <-
  max_height

grid.arrange(grob_list[["heatmap"]], grob_list[["dendrogram"]], widths = c(0.8, 0.2))
```

## Selected physicochemical properties

```{r}
knitr::kable(props)
```


## Physicochemical properties distribution

```{r fig.height = 10}
lapply(props[["prop"]], function(ith_prop) {
  plot_dat <- df_all[, c("prot", "method", "Dataset", "rep", ith_prop)] %>% 
    setNames(c("prot", "Method", "Dataset", "Repetition", "Property"))
  ggplot(plot_dat, aes(x = Repetition, y = Property, group = Repetition, fill = Dataset)) +
    geom_violin() +
    facet_wrap(~Method, ncol = 3) +
    ggtitle(props[["description"]][which(props[["prop"]] == ith_prop)]) + 
    xlab(NULL) +
    ylab(NULL) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_fill_manual("Dataset", values = c(Negative = "#76bef2", Positive = "#ff4242"))
})

```


```{r}
props <- lapply(methods, function(i) {
  lapply(1:5, function(j) {
    data.frame(t(colMeans(filter(df_all, method == i, rep == j)[, 5:(ncol(df_all)-1)]))) %>% 
      mutate(method = factor(i),
             repetition = factor(j),
             dataset = "Negative")
  }) %>% bind_rows()
}) %>% bind_rows()
props_pos <- data.frame(t(colMeans(filter(df_all, method == "Positive")[, 5:(ncol(df_all)-1)]))) %>% 
  mutate(method = "Positive", 
         repetition = "1",
         dataset = "Positive")
props_all <- bind_rows(props, props_pos) %>% 
  mutate(method = factor(method, levels = names(dataset_colors)))

pca_prop_res_all <- prcomp(props_all[, 1:(ncol(props_all)-3)], center = TRUE, scale = TRUE)

ggbiplot(pca_prop_res_all, choices = 1:2) +
  ggtitle("PCA on means of physicochemical properties with positive dataset") +
  geom_point(aes(color = props_all[["method"]], shape = props_all[["method"]]), size = 3) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Dataset", values = dataset_colors, labels = names(dataset_colors)) +
  scale_shape_manual("Dataset", values = c(17, rep(16, 13)), labels = names(dataset_colors)) 


pca_prop_res <- prcomp(props[, 1:(ncol(props)-3)], center = TRUE, scale = TRUE)

ggbiplot(pca_prop_res, choices = 1:2) +
  ggtitle("PCA on means of physicochemical properties") +
  geom_point(aes(color = props[["method"]]), size = 3) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Sampling method", values = dataset_colors)
```


```{r fig.height = 10}
df_neg %>% 
  ggplot(aes(x = ARGP820101, y = KLEP840101, color = factor(rep), fill = factor(rep))) +
  geom_jitter(aes(alpha = 0.05)) +
  stat_density_2d(aes(alpha = ..level..), geom = "polygon", color = "black", size = 0.1, adjust = 1/2) +
  facet_wrap(~method) +
  theme_bw() +
  xlab("Hydrophobicity index (Argos et al., 1982)") +
  ylab("Net charge (Klein et al., 1984)")
```

